---

- name: restart nginx
  service: name=nginx state=restarted
  when: nginx_service_state != 'stopped'


- name: reload nginx
  service: name=nginx state=reloaded
  when: nginx_service_state != 'stopped'
