---

- name: Install supervisor
  pip:
    name: supervisor
    version: "{{ supervisor_version }}"

- name: Update supervisor location
  set_fact:
     supervisorctl_bin: /usr/local/bin/supervisorctl

- name: Install packages required by non-root host setup
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"
  become: yes
  with_items:
    - cron

- name: Setup certificate related variables
  set_fact:
    pem_WILDCARD_hgi_internal_sanger_ac_uk_cert: grl-cacert.pem
    pem_WILDCARD_hgi_internal_sanger_ac_uk_key: /usr/local/share/ca-certificates/grl-cacert.crt

- name: Install requirements for running `htpasswd` ansible module
  pip:
    name: passlib
    version: 1.7.1

- name: Create directories required by non-root
  file:
    state: directory
    path: "{{ item }}"
    recurse: yes
    mode: 0775
    owner: mercury
    group: hgi
  become: yes
  with_items:
    - "{{ hgi_dir }}"
    - "{{ hgi_pkglocal_dir }}"

- name: Run common configuration for nonroot hosts
  include: nonroot.yml
  become: yes
  become_user: mercury
