#!/bin/bash

#set -euf -o pipefail
set +e
set +u
eval export OS_SOURCE_IMAGE="\${OS_SOURCE_IMAGE_${DISTRO}}"
export VERSION=$(${VERSION_COMMAND})
test -n "${IMAGE_BASENAME}" && test -n "${DISTRO}" && test -n "${VERSION}" && export PACKER_IMAGE_NAME="${IMAGE_BASENAME}-${DISTRO}-${VERSION}"
export DEPLOY_IMAGE_NAME="${PACKER_IMAGE_NAME}"
export DEPLOY_IMAGE_NAME_LATEST="${IMAGE_BASENAME}-${DISTRO}-${LATEST_VERSION_PLACEHOLDER}"
eval export PACKER_SOURCE_IMAGE_USERNAME="\${PACKER_SOURCE_IMAGE_USERNAME_${DISTRO}}"
test -r "${OS_SOURCE_IMAGE_ARTIFACT}" && export PACKER_OS_SOURCE_IMAGE="$(cat ${OS_SOURCE_IMAGE_ARTIFACT})" && echo "Set PACKER_OS_SOURCE_IMAGE=${PACKER_OS_SOURCE_IMAGE} from ${OS_SOURCE_IMAGE_ARTIFACT} artifact."
test -r "${OS_NETWORKS_ARTIFACT}" && export PACKER_OS_NETWORKS="$(cat ${OS_NETWORKS_ARTIFACT})" && echo "Set PACKER_OS_NETWORKS=${PACKER_OS_NETWORKS} from ${OS_NETWORKS_ARTIFACT} artifact."
