# Copyright (c) 2016 Genome Research Ltd.
#
# Author: Christopher Harrison <ch12@sanger.ac.uk>
#
# This file is part of hgi-ansible.
#
# hgi-ansible is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
---
# file: roles/cookie-monster/vars/main.yml

cmonster_iinit_password: "{{ cookie_monster_iinit_password }}"
cmonster_log_dir: /home/cmonster/logs

config:
  couchdb:
    url: https://cmonster:{{ cmonster_couchdb_password }}@hgi-cordon-cookie-jar.internal.sanger.ac.uk

  retrieval:
    period: 900.0

  cookiejar:
    max_requests_per_second: 500
    buffer_capacity: 1000
    buffer_latency: 50

  processing:
    max_threads: 250

  baton:
    zone: seq

  influxdb:
    host: metrics.internal.sanger.ac.uk
    port: 8086
    username: mercury
    password: "{{ cookie_monster_influxdb_password }}"
    database: hgi_cmonster
    buffer_latency: 10

  output:
    rule_log: /home/cmonster/output.log
