# Copyright (c) 2014 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-ansible.
#
# hgi-ansible is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: roles/chronos/tasks/main.yml

- name: create chronos supervisord configuration
  template: src=chronos_supervisord.conf.j2 dest={{ supervisord_conf_dir }}/chronos.conf owner=mercury group=hgi mode=0640
  notify: 
    - reload supervisord
    - restart chronos
  tags: chronos

- name: add chronos supervisord configuration to supervisord conf
  set_fact:
     supervisord_conf_includes: "{{ supervisord_conf_includes | default('') }} {{ supervisord_conf_dir }}/chronos.conf"
  notify: 
    - reload supervisord
    - restart chronos
  tags: chronos
