---

- name:  Restart the cleaner container
  become: yes
  docker_container:
    name: "{{ openstack_tenant_cleaner_container_name }}"
    image: "quay.io/wtsi-hgi/openstack-tenant-cleaner:{{ openstack_tenant_cleaner_version }}"
    state: started
    restart: yes
    command: ["{{ openstack_tenant_cleaner_docker_data_directory }}/config.yml"]
    volumes:
      - "{{ openstack_tenant_cleaner_host_data_directory }}:{{ openstack_tenant_cleaner_docker_data_directory }}"
