# Copyright (c) 2014 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-ansible.
#
# hgi-ansible is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: roles/common/handlers/main.yml

- name: generate supervisord conf
  template: src=mercury_supervisord.conf.j2 dest={{ supervisord_conf }} owner=mercury group=hgi mode=0750
  notify:
    - reload supervisord

- name: reload supervisord
  shell: "({{ supervisord_ctl }} status && {{ supervisord_ctl }} reload ) || {{ supervisord_ctl }} start"

- name: restart supervisord
  shell: "{{ supervisord_ctl }} restart || {{ supervisord_ctl }} start"

- name: update ca certificates
  become: yes
  shell: /usr/sbin/update-ca-certificates
