#!/usr/bin/env bash

set -eu -o pipefail

echo "Build openstack running packer build with: "
echo "PACKER_IMAGE_NAME: ${PACKER_IMAGE_NAME}"
echo "PACKER_OS_SOURCE_IMAGE: ${PACKER_OS_SOURCE_IMAGE}"
echo "PACKER_OS_NETWORKS: ${PACKER_OS_NETWORKS}"
echo "PACKER_SOURCE_IMAGE_USERNAME: ${PACKER_SOURCE_IMAGE_USERNAME}"
echo "PACKER_OS_SECURITY_GROUPS: ${PACKER_OS_SECURITY_GROUPS}"
echo "PACKER_OS_FLAVOR: ${PACKER_OS_FLAVOR}"
echo "PACKER_OS_FLOATING_IP_POOL: ${PACKER_OS_FLOATING_IP_POOL}"
echo "PACKER_CLOUD_INIT_WAIT_TIMEOUT_S: ${PACKER_CLOUD_INIT_WAIT_TIMEOUT_S}"
echo "PACKER_ANSIBLE_DIR: ${PACKER_ANSIBLE_DIR}"
echo "PACKER_ANSIBLE_INVENTORY_GROUPS: ${PACKER_ANSIBLE_INVENTORY_GROUPS}"

packer build ${PACKER_DEBUG} -only=openstack "${PACKER_DIR}/template-${DISTRO}.json" || (
    echo "Packer ${DISTRO} build failed, removing image '${PACKER_IMAGE_NAME}'"
    "${PACKER_DIR}/scripts/remove_failed_builds.py" --image_name="${PACKER_IMAGE_NAME}"
    exit 1
)
