#!/bin/bash

set -euf -o pipefail

SCRIPT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${SCRIPT_DIRECTORY}/common.sh"

ensureSet OS_AUTH_URL OS_USERNAME OS_PASSWORD OS_TENANT_NAME DEST_OS_PROJECT_NAME PACKER_IMAGE_NAME DEPLOY_IMAGE_NAME

export SOURCE_OS_AUTH_URL="${OS_AUTH_URL}"
export SOURCE_OS_USERNAME="${OS_USERNAME}"
export SOURCE_OS_PASSWORD="${OS_PASSWORD}"
export SOURCE_OS_PROJECT_NAME="${OS_TENANT_NAME}"
export DEST_OS_AUTH_URL="${OS_AUTH_URL}"
export DEST_OS_USERNAME="${OS_USERNAME}"
export DEST_OS_PASSWORD="${OS_PASSWORD}"

glancecp --duplicate-name-strategy=replace \
    "${SOURCE_OS_PROJECT_NAME}:${PACKER_IMAGE_NAME}" "${DEST_OS_PROJECT_NAME}:${DEPLOY_IMAGE_NAME}"
