---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Add host
      infoblox:
        server=192.168.1.1
        username=admin
        password=admin
        action=add_host
        network=192.168.1.0/24
        host={{ item }}
      with_items:
        - test01.local
        - test02.local
      register: infoblox

    - name: Do awesome stuff with the result
      debug: msg="Go crazy!"
